//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SysComedorCADE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CostosAlimentacion
    {
        public int CodCosto { get; set; }
        public string Detalle { get; set; }
        public decimal Valor { get; set; }
        public System.DateTime FRegistro { get; set; }
        public Nullable<bool> Estado { get; set; }
        public int anio { get; set; }
    }
}
