//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SysComedorCADE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EstadoCuentaPersona
    {
        public int CodEstadoCta { get; set; }
        public int anio { get; set; }
        public int CodVenta { get; set; }
        public int CodPersona { get; set; }
        public Nullable<int> pagos { get; set; }
        public decimal Valor { get; set; }
        public System.DateTime FRegistro { get; set; }
        public string usuario { get; set; }
    
        public virtual Persona Persona { get; set; }
        public virtual Venta Venta { get; set; }
    }
}
