//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SysComedorCADE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HorariosAtencion
    {
        public int CodHoario { get; set; }
        public string Detalle { get; set; }
        public Nullable<int> HorarioInicio { get; set; }
        public Nullable<int> HorarioFin { get; set; }
    }
}
