//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SysComedorCADE.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SCCADEEntities : DbContext
    {
        public SCCADEEntities()
            : base("name=SCCADEEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CostosAlimentacion> CostosAlimentacion { get; set; }
        public virtual DbSet<Entidad> Entidad { get; set; }
        public virtual DbSet<EstadoCuentaPersona> EstadoCuentaPersona { get; set; }
        public virtual DbSet<Genero> Genero { get; set; }
        public virtual DbSet<HorariosAtencion> HorariosAtencion { get; set; }
        public virtual DbSet<Persona> Persona { get; set; }
        public virtual DbSet<TipoPago> TipoPago { get; set; }
        public virtual DbSet<TipoPersona> TipoPersona { get; set; }
        public virtual DbSet<Venta> Venta { get; set; }
        public virtual DbSet<Usuarios> Usuarios { get; set; }
    }
}
