//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SysComedorCADE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Persona
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Persona()
        {
            this.EstadoCuentaPersona = new HashSet<EstadoCuentaPersona>();
            this.Venta = new HashSet<Venta>();
            this.Usuarios = new HashSet<Usuarios>();
        }
    
        public int CodPersona { get; set; }
        public Nullable<int> CodTipoPer { get; set; }
        public string NombresCompletos { get; set; }
        public string CiRuc { get; set; }
        public string Telf { get; set; }
        public string Cel { get; set; }
        public string Dir { get; set; }
        public int CodGenero { get; set; }
        public int CodEntidad { get; set; }
        public Nullable<bool> Estado { get; set; }
    
        public virtual Entidad Entidad { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EstadoCuentaPersona> EstadoCuentaPersona { get; set; }
        public virtual Genero Genero { get; set; }
        public virtual TipoPersona TipoPersona { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Venta> Venta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Usuarios> Usuarios { get; set; }
    }
}
